name: "Check Flake"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check flake
        run: nix flake check

      - name: Check formatting
        run: |
          # Find all .nix files and check formatting
          find . -name "*.nix" -type f \
            ! -path "./.git/*" \
            ! -path "./result/*" \
            ! -path "./result-*/*" \
            -exec nix fmt -- --check {} +
